language: python



python:
  - 2.6
  - 2.7
install:
  - python setup.py develop
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors -r requirements-test.txt
script:
  - python setup.py test
